
# Project Descripton

name: flutter_weater_app
description: A new Flutter project.

# Project Version
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


# Projects Dependencies
dependencies:
  flutter: # FLUTTER SDK:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Ios Icons

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0 # Lints

flutter:
  uses-material-design: true

  # Project Assets
  assets:
    - assets/icons/
    - assets/weather/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
