# Project Descripton

name: flutter_weater_app
description: A new Flutter project.

# Project Version
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Projects Dependencies
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  sleek_circular_slider: ^2.0.1

dev_dependencies:

  flutter_lints: ^2.0.0 # Lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Project Assets
  assets:
    - assets/icons/
    - assets/weather/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
